apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-cd
spec:
  interval: 2m
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
